spring:
  datasource:
    url: jdbc:h2:mem:crypto
    username: miktia
    password: nadvorje
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    root: INFO
scheduler:
  cron: "0 * * * * *"